# Generated by Django 4.2.5 on 2023-11-15 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Rating must be between 1 and 5.', regex='^[1-5]$')]),
        ),
    ]
